data:extend({
    {
        type = "int-setting",
        name = "sei-electric-mining-drill-resource-drain-rate",
        setting_type = "startup",
        default_value = 100,
        minimum_value = 1,
        maximum_value = 100,
        order = "a",
    },
    {
        type = "int-setting",
        name = "sei-kr-electric-mining-drill-mk2-resource-drain-rate",
        setting_type = "startup",
        default_value = 90,
        minimum_value = 1,
        maximum_value = 100,
        order = "b",
        hidden = true,
    },
    {
        type = "int-setting",
        name = "sei-area-mining-drill-resource-drain-rate",
        setting_type = "startup",
        default_value = 80,
        minimum_value = 1,
        maximum_value = 100,
        order = "c",
        hidden = true,
    },
    {
        type = "int-setting",
        name = "sei-kr-electric-mining-drill-mk3-resource-drain-rate",
        setting_type = "startup",
        default_value = 70,
        minimum_value = 1,
        maximum_value = 100,
        order = "d",
        hidden = true,
    },
    {
        type = "int-setting",
        name = "sei-big-mining-drill-resource-drain-rate",
        setting_type = "startup",
        default_value = 50,
        minimum_value = 1,
        maximum_value = 100,
        order = "e",
        hidden = true,
    },
})